### ISSUE TITLE
App ID hardcoded in GetSignedJwtToken function

### ISSUE THREAD

**Issue by johnmccabe** [alexellis/derek#10]
## Expected Behaviour

Following the README should be sufficient to deploy and run your own Derek instance.

## Current Behaviour

The generated JWT tokens are invalid.

## Possible Solution

Replace the hardcoded App ID in `jwt_auth.go` with one sourced from the env.

## Context

Unable to get own Derek instance running, positive side tho is that I now know a lot more about Githubs App auth 😄 

## Your Environment

* Docker version `docker version` (e.g. Docker 17.0.05 ):
17.06.1-ce

* Are you using Docker Swarm or Kubernetes (FaaS-netes)?
Swarm

* Operating System and version (e.g. Linux, Windows, MacOS):
Ubuntu 17.04 on DigitalOcean

* Link to your project or a code example to reproduce issue:
n/a

**Comment by johnmccabe** [comment]
I've fixed this locally, will raise a PR shortly

**Comment by johnmccabe** [comment]
Derek add label: bug

**Comment by johnmccabe** [comment]
@alexellis this can be closed

**Comment by rgee0** [comment]
Derek close

**Comment by alexellis** [comment]
Derek add label: notdeployedommypersonalaccount

**Comment by rgee0** [comment]
I'm not in maintainers even if he was

**Comment by alexellis** [comment]
Do a PR to add yourself
