### ISSUE TITLE
Refuse DCO for users.noreply.github.com

### ISSUE THREAD

**Issue by alexellis** [alexellis/derek#118]
## Expected Behaviour

The DCO requires a valid email address and not an anonymous entity.

## Current Behaviour

Some users put `user@users.noreply.github.com` to obstinate their real email address rendering it useless for the purposes it is required.

## Possible Solution

Add the `no-dco` label and a comment about the use of an anonymous email.

## Steps to Reproduce (for bugs)

1. Sign off a commit as "Name <user@users.noreply.github.com>" and see Derek accept that

**Comment by martindekov** [comment]
We might send another message if `noreply.github.com` exists in the commit body like
`Thank you for the commit, but it seems like the email is anonymous...`

**Comment by matipan** [comment]
How about:
```
Thank you for your contribution. I've just checked and one or more of your commits appear to be signed-off by an anonymous email. Please consider signing your commits with a valid email address. That's something we need before your Pull Request can be merged
```
?
I'll begin making the changes to add a different message for this case :smile:

**Comment by alexellis** [comment]
I'd like to keep it brief and concise

**Comment by matipan** [comment]
PR raised: #120
