### ISSUE TITLE
Suggestion: consolidate "What can I do?" with user guide

### ISSUE THREAD

**Issue by alexellis** [alexellis/derek#121]
## Suggestion

Can we consolidate the README's "What can I do?" section with the user guide by using a link?

Alex

**Comment by alexellis** [comment]
@rgee0 @matipan wdyt?

**Comment by rgee0** [comment]
Fixed in https://github.com/alexellis/derek/commit/bda232e3bc589a0fac756151dfc158aec60b5e87
