### ISSUE TITLE
Run Derek container as non-root user

### ISSUE THREAD

**Issue by alexellis** [alexellis/derek#128]
## Expected Behaviour

Run Derek as non-root user instead of `root`

## Current Behaviour

Derek runs as root

## Possible Solution

See how we do this for the Golang template in openfaas/templates and copy the approach.

**Comment by alexellis** [comment]
Dockerfile for the edit: https://github.com/alexellis/derek/blob/master/Dockerfile

Non-root example from OpenFaaS: https://github.com/openfaas/templates/blob/master/template/go/Dockerfile#L27

**Comment by martindekov** [comment]
Derek assign: me
