### ISSUE TITLE
Support for other environments

### ISSUE THREAD

**Issue by jhernandezb** [alexellis/derek#13]
Would you be open to add examples for deploying it to AWS Lambda with something like [apex/up](https://github.com/apex/up) or [zeit/now ](https://zeit.co/now). I probably could help with those.

**Comment by elliott-beach** [comment]
This is another use case for being able to deploy OpenFaas on AWS, then this wouldn't be an issue.

**Comment by alexellis** [comment]
Derek add label: priority/low

**Comment by alexellis** [comment]
Derek close: marking as inactive - we've not seen not much interest or call for this
