### ISSUE TITLE
Add 1 min safety window for commit listing

### ISSUE THREAD

**Issue by alexellis** [alexellis/derek#143]
## Expected Behaviour

Derek shouldn't include commits from prior releases

## Current Behaviour

He does

## Possible Solution

Add 1 min safety window for commit listing

## Steps to Reproduce (for bugs)

Sometimes commits get leaked into the notes from the previous release

1. https://github.com/openfaas/faasd/releases/tag/0.7.8
2. https://github.com/openfaas/faasd/releases/tag/0.7.7

**Comment by alexellis** [comment]
Here's the code:

https://github.com/alexellis/derek/blob/b30606c1d2761ba04cb076c98177ed0b1c6dd5a9/handler/release_handler.go#L64

We need to take the approach for PRs which adds a small window for error:

https://github.com/alexellis/derek/blob/b30606c1d2761ba04cb076c98177ed0b1c6dd5a9/handler/release_handler.go#L190

And apply that to the commit listing.

**Comment by rgee0** [comment]
Derek Close: Fixed in #145

**Comment by rgee0** [comment]
Derek close: Fixed in #145
