### ISSUE TITLE
Derek adds a label when labelling comment is deleted

### ISSUE THREAD

**Issue by rgee0** [alexellis/derek#15]
Course of action to reproduce:

`Derek add label: fred` <-- label added
`Derek remove label: fred` <-- label removed
Delete comment 1 <-- label added again

Potential fix would be to inspect the POSTed JSON to see if `"action": "deleted"` is set and cause Derek to refuse to act within `AddLabel` and `RemoveLabel` in this instance.  Within the code this would be `req.Action`

**Comment by alexellis** [comment]
Happy for you to work on this if you have time.

**Comment by alexellis** [comment]
Can we add a test for this?
