### ISSUE TITLE
Add Derek to two new organizations (vielmetti, tinkerbell)

### ISSUE THREAD

**Issue by vielmetti** [alexellis/derek#152]
PR to follow.

**Comment by alexellis** [comment]
Thanks @vielmetti, I wasn't sure what was happening so I have added both in via https://github.com/alexellis/derek/commit/83eea02affc6b5f34c2676d9b93864f0c28e5702

Hope I haven't stepped on your toes and that the spelling is right.

**Comment by vielmetti** [comment]
Thanks!

**Comment by alexellis** [comment]
Please see our OpenFaaS example as a starting-point for a DEREK file https://github.com/openfaas/faas/blob/master/.DEREK.yml

Or Inlets - https://github.com/inlets/inlets/blob/master/.DEREK.yml
