### ISSUE TITLE
Derek should handle more than 1 command in once.

### ISSUE THREAD

**Issue by TheYkk** [alexellis/derek#154]
## Expected Behaviour
Derek should handle more than 1 command in once.

## Current Behaviour
It doesn't
![image](https://user-images.githubusercontent.com/21688838/86412911-9eaf6f80-bcc8-11ea-864a-9cd473b8a121.png)

## Your Environment

- [x ] You're using the hosted Derek service

**Comment by alexellis** [comment]
Whilst this might sound nice, we've so far decided against it. Fyi some of the commands like add label do support multiple arguments. 

I'm going to close the issue, but we'll track interest from users here.

**Comment by alexellis** [comment]
/set title: Feature request: give multiple commands within a single comment
