### ISSUE TITLE
[Bug] Regression in authentication code

### ISSUE THREAD

**Issue by alexellis** [alexellis/derek#156]
## Expected Behaviour

API tokens should be obtained per installation for reading beyond the 50 requests per hour limit, and for writing back to the repos where Derek is operational

## Current Behaviour

The API token is not being created correctly and Derek has been broken and not operating since deploying 0.9.15 with #155 

## Possible Solution

Test the code change in #155 thoroughly (end to end) and fix any issues.

## Steps to Reproduce (for bugs)

1. Deploy 0.9.15
2. Create a release and see no release notes
3. See the rate limit printed as N/50 not N/5000
4. Try to add a label and see it fail

## Context

This will block all future PRs until fixed or reverted.

With 0.9.15

<img width="1585" alt="Screenshot 2020-07-23 at 09 07 28" src="https://user-images.githubusercontent.com/6358735/88264617-f8053000-ccc3-11ea-8141-7bf4d15797f2.png">
<img width="1585" alt="Screenshot 2020-07-23 at 09 07 03" src="https://user-images.githubusercontent.com/6358735/88264618-f89dc680-ccc3-11ea-93f5-ffd4f20c63f9.png">

When reverting to previous version:

<img width="1170" alt="Screenshot 2020-07-23 at 09 03 36" src="https://user-images.githubusercontent.com/6358735/88264509-c724fb00-ccc3-11ea-8c32-70695ee6487d.png">
<img width="462" alt="Screenshot 2020-07-23 at 09 01 39" src="https://user-images.githubusercontent.com/6358735/88264523-ca1feb80-ccc3-11ea-8cfe-5c2cfa95f247.png">

**Comment by alexellis** [comment]
@Waterdrips please take a look?

cc @martindekov

**Comment by Waterdrips** [comment]
`apps` --> `app` in the new url  (I put apps, should have been app)

PR opened that fixes this, tested in new derek installation.

**Comment by alexellis** [comment]
Thank you for the quick turn-around on this Alistair 💪

**Comment by Waterdrips** [comment]
/close
Forgot to link the close to the PR.
