### ISSUE TITLE
Switch to using go modules

### ISSUE THREAD

**Issue by techknowlogick** [alexellis/derek#160]
## Current Behaviour
Currently the project using `dep` to manage dependencies.

## Possible Solution
By switching to go modules it would bring dependency management to align with go ecosystem. 

It seems that at least some OpenFaaS repos still use dep, although arkade uses go modules. Would you accept a PR that upgrades Derek to use go modules? If not that's ok and this can be closed. Per `CONTRIBUTING.md` I opened this issue first before sending a PR.

**Comment by alexellis** [comment]
Go for it. We are slowly migrating to go modules, but in some circumstances retaining the vendor folder. -mod=dep can be used here to keep the build fast.

Yes I know that some developers can't stand the thought of that 😉

Many of the openfaas community projects are using modules. Help with the task would be appreciated

**Comment by alexellis** [comment]
And are you considering using Derek too?

**Comment by techknowlogick** [comment]
> And are you considering using Derek too?

Not for the Gitea project, but I have some personal projects that Derek could help with, and I figure I could also look into adding support for Gitea so that for self-hosted Gitea installs those users could use Derek too.
