### ISSUE TITLE
Detect repository default branch

### ISSUE THREAD

**Issue by angelbarrera92** [alexellis/derek#168]
## Expected Behaviour
I expect derek to look for its configuration file on the default branch of the repository instead of `master`.
GitHub changed its default branch from `master` to `main`, it is difficult to debug this issue if you don't run derek self-hosted.

## Current Behaviour
derek looks for the `.DEREK.yml` file in the root of the project in the `master` branch.

## Possible Solution
Identify what is the default branch of the repository, then look for the configuration file on that branch.

## Steps to Reproduce (for bugs)
1. Create a new repository
2. Setup derek in the default branch
3. Create a GitHub issue on the new repository
4. Add a comment requesting derek to add a label

## Context
During some derek modifications, I found this issue. Thanks that I self-hosted it I was able to find the misconfiguration in my repository.

## Your Environment

- [ ] You're using the hosted Derek service

or

- [ ] You host your own OpenFaaS cluster with Derek installed
- [X] I deployed a copy of Derek in a simple container without openfaas.

**Comment by jolheiser** [comment]
@alexellis Hello! 👋 

I would like to contribute to this issue. The  webhook payload actually should contain the repository's default branch, so that should be easy enough to work with.

Anything you want me to consider, or does that all sound alright with you?

**Comment by alexellis** [comment]
Hi @jolheiser 

What approach do you think would make sense?

If this can be done without using up API calls, I'd be interested in a draft PR for discussion. 

Alex

**Comment by jolheiser** [comment]
This was resolved by #174 

Thanks again @cpanato @alexellis !

**Comment by rgee0** [comment]
Derek close: Fixed in #174
