### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by alexellis** [alexellis/derek#170]
## Feature

Migrate to GitHub Actions

## Why is this required?

Travis no longer provides an unlimited free tier, and the openfaas community has now migrated away.

See openfaas/faas-cli or openfaas/faas for an example of how to publish a Go container. No binaries are required.

**Comment by alexellis** [comment]
@utsavanand2 could you run with this please?

**Comment by cpanato** [comment]
@alexellis this one is open for grabs?

**Comment by alexellis** [comment]
Hi @cpanato, since Derek is a function, I would suggest that you implement it as per: https://github.com/alexellis/faasd-example/blob/master/.github/workflows/build.yml

But, there is no need to push an image in the build flow, so separate them out:

CI - build / test
Publish - build / test / publish

Here's an example that does both in separate files: https://github.com/openfaas/faas/tree/master/.github/workflows
