### ISSUE TITLE
.DEREK.yml feature flags + maintainers list

### ISSUE THREAD

**Issue by alexellis** [alexellis/derek#21]
The .DEREK.yml file should take over the place of the MAINTAINERS file.

This will support roles / actions and mapping users to roles, but initially will look like this:

```
maintainers:
 - alexellis
 - rgee0
features:
 - dco_check
 - comments
```

See 2.0 extensions - https://github.com/alexellis/derek/issues/22

**Comment by alexellis** [comment]
@rgee0 I think this is what we need to do next - the dco toggle will be important for repos where they already have a bot doing this. cc/ @thaJeztah

**Comment by rgee0** [comment]
Derek assign: rgee0

**Comment by alexellis** [comment]
I'm not sure why but you're not in the list for me to assign to.

**Comment by rgee0** [comment]
From https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/

> If you have write access to a repository, you can assign issues and pull requests to yourself, collaborators on personal projects, or members of your organization with read permissions on the repository.

**Comment by rgee0** [comment]
Derek close

**Comment by rgee0** [comment]
I keep doing that!

**Comment by alexellis** [comment]
Doing what?

**Comment by rgee0** [comment]
Typing `Derek do something` on this repo.

**Comment by rgee0** [comment]
Derek close
