### ISSUE TITLE
Posibility to pass multiple values to an action

### ISSUE THREAD

**Issue by itscaro** [alexellis/derek#32]
It would be great to be able to send multiple values in the same action, i.e:

`Derek add label: UX, enhancement, proposal` (`,` as separator, more natural)
or
`Derek add label: UX || enhancement || proposal` (`||` as separator)

I can work on this if the proposal is accepted

**Comment by itscaro** [comment]
Derek add label: proposal

**Comment by rgee0** [comment]
Derek add label: proposal

**Comment by alexellis** [comment]
I can see this could reduce verbosity if you wanted to take several actions at once, but I don't want Derek to become a DSL or overly-complex. Perhaps the answer is to allow new-line separated commands within a single comment. This does complicate things though as we "panic" / exit in multiple places.

Let's prioritise the most important work first.

**Comment by alexellis** [comment]
Derek add label: priority/low

**Comment by alexellis** [comment]
We could look at doing this with a separator like a comma.

   D3r3k add label: proposal, priority/low, area/ux

Just trim spaces.

**Comment by rgee0** [comment]
Derek add label: PR
