### ISSUE TITLE
Proposal: send messages to Slack channel

### ISSUE THREAD

**Issue by alexellis** [alexellis/derek#36]
In order to monitor and observe usage of Derek we should offer the ability to send messages to a Slack channel.

All usage of Derek via comments / PRs is public so I do not see any concerns with this going to one place.

It will give an overview at a glance whether there is any recent activity, by which installations and which users. 

Example of status messages sent to Slack:

* a no-dco label is added to PR 131 in repo openfaas/faas-cli
* a label is applied to issue 586 on the openfaas/faas repo by @alexellisuk

This would use the incoming web hooks feature rather than any specialist library and could be swapped for any other HTTP endpoint. Slack messages have a basic format of:

```json
{
   "text": "Message to channel goes here"
}
```

**Comment by rgee0** [comment]
On a similar theme... https://github.com/blog/2506-slack-and-github-your-ultimate-productivity-pair

**Comment by sesam** [comment]
I'm trying to understand the comment above about one channel in one Slack space that can track many installations (and users).
For what I know, to be able to post to slack, the slack client you need at minimum some keys or access tokens. Would you give out, and ask nicely, that everyone who deploys Derek to somewhere would insert the keys for your channel so you see their usage of Derek?

**Comment by alexellis** [comment]
Hi Simon,

What's your interest in Derek?

Alex

**Comment by sesam** [comment]
Depending on how it works, either a drive-by visit over a few days to see if this is still alive and kicking, or if it works out well, I might have an organisation that could make use of this. I'm liking the idea of minimising access rights. Where are you using Derek currently? I'm good at git, beginner at go. could revive this slack feature if you still want to have it implemented. Though if your installation is huge, some rate limiting would be needed, like maybe skipping dco/no-dco messages as a start.

**Comment by alexellis** [comment]
Is Derek "alive and kicking", yes it's used on all the repos and orgs listed on the README and an essential part of the openfaas community.

**Comment by alexellis** [comment]
Closing this issue due to a lack of demand
