### ISSUE TITLE
Refactoring: Read secrets from OpenFaaS secrets

### ISSUE THREAD

**Issue by alexellis** [alexellis/derek#41]
Right now secrets need to be built into a local/private image or bind-mounted. Derek should read secrets from the OpenFaaS `/run/secrets/` folder which happens to be the same on Kubernetes and Swarm alike.

Secrets:

* GitHub symmetrical secret used for checking the HMAC
* Cert / pem file used for authenticating to the GitHub API via OAuth

**Comment by alexellis** [comment]
Since we run this only inside an OpenFaaS function container I think it's OK to read from a set path. No need to make it configureable.

**Comment by alexellis** [comment]
@rgee0 are you taking this?

**Comment by rgee0** [comment]
I'm looking at this

**Comment by rgee0** [comment]
Derek add label: PR
