### ISSUE TITLE
Add support for `assign reviewer`

### ISSUE THREAD

**Issue by ivanayov** [alexellis/derek#48]
At the moment Derek cannot assign reviewers to a pull request.

Support comments like:
```
Derek assign reviewer: username
```

Good option is to make it work with a list of users:
```
Derek assign reviewer: user1, user2
```

**Comment by rgee0** [comment]
How would this feature behave when the requested reviewer isn't part of the org?

**Comment by alexellis** [comment]
@rgee0 it wouldn't work, just like when you try to do this through the UI and the reviewer is not in the org.

**Comment by rgee0** [comment]
Thanks @alexellis.  The thinking was more directed towards the feature - how would the user receive feedback to that effect, i.e. to avoid Derek getting the blame / issues being raised?

**Comment by alexellis** [comment]
This has been released and is in use
