### ISSUE TITLE
Add more docs for "Github app" section of install

### ISSUE THREAD

**Issue by OmgImAlexis** [alexellis/derek#51]
I'm a little stuck on the "Install Derek as a GitHub app" section as I can't find it on the marketplace as most "Github apps" are.

So then I'm guessing I have to create my own Github app? If so could you help with what these fields will needs to be filled with.

I already have a publicly facing openfaas gateway that I can use.

(Also might be an idea to link to the Github app registration page.)
https://github.com/settings/apps/new

&nbsp;

![screen shot 2018-04-20 at 3 09 56 pm](https://user-images.githubusercontent.com/6525926/39032545-2abeea00-44ad-11e8-94ae-89045b043ff4.png)
![screen shot 2018-04-20 at 3 12 40 pm](https://user-images.githubusercontent.com/6525926/39032582-4d2dba30-44ad-11e8-83cf-2ec0e62a4999.png)

![screen shot 2018-04-20 at 3 10 07 pm](https://user-images.githubusercontent.com/6525926/39032546-2b8c90a4-44ad-11e8-9f41-b47187742e27.png)

**Comment by OmgImAlexis** [comment]
So I finally got it working.

```
2018/04/20 13:28:09 stderr: time="2018-04-20T13:28:09Z" level=fatal msg="No customer found for: pymedusa/test-repo"
```

Seems the customer list is hardcoded. Should I just disable it via the env?
https://github.com/alexellis/derek/blob/d1dc963fea622554ae940f0892427cc6cde54dea/auth/customers.go#L21

**Comment by alexellis** [comment]
@OmgImAlexis are you trying to host your own Derek or use our shared SaaS?

**Comment by alexellis** [comment]
The documentation in this site says to contact me for access to the shared instance... I'll take this issue as you doing that. Look at the Slack channel #derek - it has the public URL where you can install the hosted GitHub app.

> Get your own Derek robot
> You can host and manage your own Derek robot using these instuctions, or use our managed service. **To use our managed service get in touch with Alex Ellis for more info.**

**Comment by alexellis** [comment]
> It'd be great for the docker container to log more useful info be default. Maybe I should open a separate issue on that?

While this sounds useful I'm not sure it's actionable. If there is a specific thing you'd like to do perhaps we can target that instead?

What is the reason for self-hosting over using the free SaaS version?

**Comment by OmgImAlexis** [comment]
Mainly which feature was being used and by who I was expecting to see more of a HTTP type log instead of what was presented. The reason I wanted this is so I could parse the logs for my grafana install.

I like to self-host all of my infrastructure.

**Comment by alexellis** [comment]
Derek close: resolved
