### ISSUE TITLE
Allow custom URL via env-var for customer validation

### ISSUE THREAD

**Issue by alexellis** [alexellis/derek#52]
## Expected Behaviour

Anyone can host their own Derek and also validate their own customer list

## Current Behaviour

The code will validate against [our list](https://github.com/alexellis/derek/blob/d1dc963fea622554ae940f0892427cc6cde54dea/auth/customers.go#L21).

## Possible Solution

There is a workaround though - just disable customer validation via the existing env-var flag. 

I'd suggest we allow the customer list URL to be supplied via env-var too.

Related #51

**Comment by rgee0** [comment]
I’ll pick this up. 

https://github.com/alexellis/derek/blob/32ab31824e44ce93b8e3eb9ff014deaac5c4ef4b/auth/customers.go#L21

I take it we want to take env var if set or default to the current value?

**Comment by alexellis** [comment]
I think that would be a good approach
