### ISSUE TITLE
Tag PRs from new contributors as derek/first-time

### ISSUE THREAD

**Issue by alexellis** [alexellis/derek#65]
This is a suggestion to help with first impressions and helping new contributors to a project/repo.

To help users identify and give help to new contributors to a repository Derek could add a label such as `derek/first-time` or `derek/new-contributor`

This metadata may be represented in the metadata already of a GitHub push/PR - https://developer.github.com/v3/activity/events/types/#pushevent

Alex

**Comment by alexellis** [comment]
What do you think @rgee0 @neolit123 ?

**Comment by alexellis** [comment]
Once a PR has been merged the status moves to something like "collaborator" and this wouldn't be applied again after that point.

**Comment by mrtind** [comment]
I can try to pair with @ivanayov on this one.

**Comment by alexellis** [comment]
Sure, please look at the GitHub APIs together to see if this data is present in the push or PR payloads.

**Comment by mrtind** [comment]
@alexellis  I looked through the webhooks and the field "before:" is filled with 000000000000 if you push for the first time.I tried it with clean repository two times to be sure.

**Comment by alexellis** [comment]
That is the first commit right? What about whether the PR submitter is a first timer on the repo.

**Comment by mrtind** [comment]
This happens if you push for the first time in the repo.You can have many commits but if its your first push the before value will be 0.

**Comment by mrtind** [comment]
No mistake its 0 for a branch.I will continue to search.

**Comment by rgee0** [comment]
In the create event have a look at the `"author_association"` field. @mrtind

**Comment by alexellis** [comment]
Where did you see that @rgee0 sounds useful

**Comment by rgee0** [comment]
I looked into how github generate the labels on the comments and apparently that field feeds it.  its available in the `pull_request` event WH in link you provided above:

https://developer.github.com/v3/activity/events/types/#pushevent

**Comment by mrtind** [comment]
It seems like the author_association is OWNER or NONE in the webhooks tested by me and Ivana it only shows those two even when she had her first pull request towards my repo.The problem with the push webhooks is that it shows information for the current branch you are pushing in so for that branch you are new contributor and its not useful.If you have something in mind @rgee0 ? Maybe im missing something.

**Comment by rgee0** [comment]
Did you try merging a PR and inspecting the value? I’d expect to see `none` or `owner` or `contributor`. Someone showing `none` on creation of a `pull_request`would be a first time contributor.

I wouldn’t get too hung up on the `push` event I think the `pull_request` event WH gives us what we’re looking for.

**Comment by mrtind** [comment]
Thank you @rgee0 for the help! The status changed to CONTRIBUTOR i just missed that pull request event triggers on open and close and thought that Ivana had 2 pull requests on my repo.

**Comment by alexellis** [comment]
My suggestion is to add the label at the start then leave it there. I don't think the subsequent events need matter and GitHub will advise in the header or context if it was opened or closed.

**Comment by rgee0** [comment]
Derek close
