### ISSUE TITLE
Suggestion: support manipulation of milestones

### ISSUE THREAD

**Issue by dirkhh** [alexellis/derek#74]
Derek already supports manipulation of Labels. The GitHub API for Milestones is very similar. Milestones are used to group issues that belong together as a feature or a deliverable. See here for the distinctions: https://guides.github.com/features/issues/

## Expected Behaviour

`Derek set milestone: 4.8` should add the named milestone to the current issue
`Derek remove milestone: 4.8` should accordingly remove the milestone

## Current Behaviour

Milestones aren't supported at all

## Possible Solution

Add code analogous to the `Label` handling.

## Context

Subsurface is starting to use Milestones to group issues that we want to address for upcoming releases and it would be very useful if more people were able to set/remove milestones from issues, without being Collaborators on the project

## Your Environment

- [x] You're using the hosted Derek service

or

- [ ] You host your own OpenFaaS cluster with Derek installed

**Comment by neolit123** [comment]
@mrtind please, have a look and share any comments or questions that you may have :+1:

**Comment by alexellis** [comment]
Hi @mrtind Thanks for looking into this.

What struct/object does "CreateMilestone" live on?

I would think we are not creating milestones here, but adding them to existing issues or PRs. This may need you to call something like "update issue" rather than AddMilestoneToIssue().

**Comment by mrtind** [comment]
It lives on IssuesService the same for AddLabelsToIssue().

**Comment by neolit123** [comment]
@mrtind 

apparently milestones are slightly different.

first you have to enumerate them:
https://github.com/google/go-github/blob/master/github/issues_milestones.go
using `ListMilestones`, which will return a list of `Milestone` objects. important elements are `Title` and `Number`.

so if the user types:
`Derek set milestone: 4.8`
we need to use `ListMilestones` to find the `Number` of that milestone with `Title` == `4.8`.

once you know the number you can add this milestone to an issue using `Edit` for an issue:
https://github.com/google/go-github/blob/master/github/issues.go#L288
and an `IssueRequest` object.

the `IssueRequest` object has a `Milestone` field, for example:

```
input := &IssueRequest{
    Milestone: github.Int(1)
}
```
would set the milestone fro that issue to `Number = 1`.
to remove a milestone from an issue, i think it's either `nil` or `Int(0)`, because this is an int pointer in `go-github`.

```
input := &IssueRequest{
    Milestone: nil // or github.Int(0)
}
```

and here is how you use `Edit`:
https://github.com/google/go-github/blob/master/github/issues_test.go#L235

the `go-github` library does not have unit tests for this, so not sure how well it's tested and supported.

let me know of further questions, thanks.

**Comment by mrtind** [comment]
Thanks @neolit123 for pointing this out, apparently I was heading in the wrong direction...

**Comment by alexellis** [comment]
Great analysis @neolit123 that is really helpful and detailed. 

Martin, I would suggest trying this out in an isolated example/repo to see if it works - or hard-coding it into Derek and testing it on your DigitalOcean instance so that you can get some confidence before proceeding. 

Alex

**Comment by mrtind** [comment]
Yeah that I managed to set label in own repo with derek. Now i must find a way to remove it and create tests.

**Comment by alexellis** [comment]
Does the example from Lubomir help of setting the value to 0/nil?

**Comment by mrtind** [comment]
When i manually remove milestone i see the webhook "milestone":null, ... but when i set milestone *int to nil it does not solve the issue. I will try again obviously the milestone field must be null i must find a way to set it to null.

**Comment by neolit123** [comment]
@mrtind 

i predicted, `nil` or `0` would not work. see:
https://github.com/google/go-github/issues/236

we have to do a workaround. ^ there is a proposed solution in there to use a `PATCH` request directly.
https://developer.github.com/v3/?#http-verbs

`A PATCH request may accept one or more of the attributes to update the resource`

the function calls in the workaround are here:
https://github.com/google/go-github/blob/master/github/github.go#L295
https://github.com/google/go-github/blob/master/github/github.go#L455 (note that this needs Context e.g. context.Background())

so the idea is to basically PATCH out the milestone JSON from the issue JSON.

**Comment by alexellis** [comment]
I believe that one of the examples suggested using a custom struct, would that work?

**Comment by neolit123** [comment]
do you mean a custom struct instead of the anonymous struct in the workaround?

**Comment by mrtind** [comment]
@alexellis  @neolit123  I managed to remove the label but the patch of code that is workaround looks ugly. Should i make a function instead of that block of code ?

**Comment by neolit123** [comment]
hard to say without seeing your code. better wait before it's made into a PR.

**Comment by neolit123** [comment]
@mrtind
i was about to comment further here, but i see that you've already submitted a PR.
nice! progressing fast! :)

**Comment by alexellis** [comment]
Hi all, I'd like to let you know that the PR raised by @mrtind has been merged and released, thanks to everyone who helped on this feature. 

Derek is now live and I've started setting up some milestones for Derek features & tweaks. Great job Martin!

Alex

**Comment by alexellis** [comment]
Derek close: released 🎉

**Comment by dirkhh** [comment]
Thanks @mrtind  - great work!
