### ISSUE TITLE
Move Derek to latest Golang version

### ISSUE THREAD

**Issue by alexellis** [alexellis/derek#77]
## Task:

1. Try moving the Derek Dockerfile to the latest Go version and build.
2. Fix any issues
3. Send PR

**Comment by alexellis** [comment]
@mrtind here's a small one that would be great while you're on a roll.

**Comment by alexellis** [comment]
Derek set milestone: 0.6.0

**Comment by alexellis** [comment]
Look at the tags of Docker images on the Hub for this variant of Go which is being used.

**Comment by mrtind** [comment]
https://hub.docker.com/_/golang/ I was searching in here and I cant seem to find bigger than 1.9.7-alpine? You ment change 1.9 with 1.10 ?

**Comment by alexellis** [comment]
Yes that is what I meant by latest (but don't use the beta)

Can you add this to your tasks for this week please?

Thanks.

Alex

**Comment by rgee0** [comment]
Derek close: addressed in #83
