### ISSUE TITLE
Add support for assigning and unassigning issues/PRs

### ISSUE THREAD

**Issue by johnmccabe** [alexellis/derek#8]
## Expected Behaviour
Derek should be able to assign and unassign issues and PRs, with the target `me` as a shortcut for the maintainer who issued the request.
```
Derek assign: me
Derek assign: alexellis
Derek unassign: me
Derek unassign: alexellis
```

**Comment by johnmccabe** [comment]
I've picked this up today

**Comment by alexellis** [comment]
Great idea. It'd be good to be about to use the word me.

Derek unassign me

Tests are always appreciated too if you have time

**Comment by johnmccabe** [comment]
Derek add label: enhancement
