### ISSUE TITLE
Prevent removal of "no-dco" label

### ISSUE THREAD

**Issue by alexellis** [alexellis/derek#85]
I noticed that a contributor had Derek installed on one of his repos. He had a PR arrive without sign-off and Derek added the no-dco label.

The developer removed the label then merged the PR.

I would suggest that we prevent Derek from responding to "Derek remove label: no-dco" for the above reason.

Those with write-access can still remove it via the UI controls.

**Comment by alexellis** [comment]
@martindekov would you like to work on this next week?

**Comment by martindekov** [comment]
Yeah
