### ISSUE TITLE
Add support for closing/reopening issues/PRs

### ISSUE THREAD

**Issue by johnmccabe** [alexellis/derek#9]
## Expected Behaviour
Derek should allow Maintainers to close and reopen issues and PRs.
```
Derek close: mandatory reason text
Derek reopen: mandatory reason text
```

**Comment by alexellis** [comment]
Derek add label: hacktoberfest

**Comment by johnmccabe** [comment]
I'll pick this up

**Comment by alexellis** [comment]
Thanks

**Comment by johnmccabe** [comment]
FYI - refer to the comments in this PR regarding RBAC

https://github.com/alexellis/derek/pull/12
