### ISSUE TITLE
Add Travis (build status) badge to readme

### ISSUE THREAD

**Issue by alexellis** [alexellis/derek#98]
Add Travis (build status) badge to readme

Available via: https://travis-ci.org/alexellis/derek

**Comment by qnoox** [comment]
Hello, Will fix this 👍

**Comment by alexellis** [comment]
Thank you! Please do read the contribution guide first.

**Comment by dgisser** [comment]
@alexellis is this completed? It looks like appears as though the readme has the build status badge.

**Comment by alexellis** [comment]
Looks like I was mistaken and it is there, maybe it didn't render on my browser. Let's add the godoc badge instead?
